yarnPath: '.yarn/releases/yarn-berry.cjs'
nodeLinker: 'node-modules'
npmPublishAccess: 'public'
npmPublishRegistry: 'https://registry.npmjs.org'
npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
  "@algolia/autocomplete-preset-algolia@*":
    peerDependenciesMeta:
      "@algolia/client-search":
        optional: true
  "@docusaurus/theme-common@*":
    peerDependenciesMeta:
      "prism-react-renderer":
        optional: true
  "fork-ts-checker-webpack-plugin@*":
    peerDependenciesMeta:
      "typescript":
        optional: true
      "webpack":
        optional: true

