#!/bin/bash

find ./ -name "*.v" | xargs -i -t cp -fr {} ./src/
find . -path ./test -prune -o -name '*.js' -print | xargs ...
find . -type d \( -path dir1 -o -path dir2 -o -path dir3 \) -prune -o -name "*.[chS]" -print | xargs ...
