import solution from './0389'

/**
 * @author sabertazimi
 * @license MIT
 * @level easy
 * @description find-the-difference
 * @see {@link https://leetcode-cn.com/problems/find-the-difference/}
 * You are given two strings s and t.
 * String t is generated by random shuffling string s
 * and then add one more letter at a random position.
 * Return the letter that was added to t.
 */
describe('leetCode [0389]', () => {
  it('should AC', () => {
    expect(solution('', 'y')).toStrictEqual('y')
    expect(solution('a', 'aa')).toStrictEqual('a')
    expect(solution('ae', 'aea')).toStrictEqual('a')
    expect(solution('abcd', 'abcde')).toStrictEqual('e')
  })
})
